function handleException(status){
    console.log(status);
}

export { handleException };